#pragma once

#pragma warning(push)
#include <Windows.h>
#include <synchapi.h>
#pragma warning(disable: 5105)
#pragma warning(pop)
#include <queue>
#include <vector>
#include <bitset>
#include <unordered_map>
#include <stdio.h>
#include <assert.h>
#include <type_traits>
#include <optional>
#include <chrono>
#include <iostream>
#include <filesystem>
#include <array>
#include <functional>
#include <type_traits>
#include <fstream>
#include <atomic>
#include <locale>
#include <codecvt>
#include <iomanip>
#include <sstream>
#include <numeric>
#pragma warning(push, 0)
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "glm.hpp"
#include "gtc/quaternion.hpp"
#include "gtc/type_ptr.hpp"
#include "gtx/euler_angles.hpp"
#include "stb_image.h"
#include "json.hpp"
#pragma warning(pop)
#include "Core.h"
#include "BamboPaths.h"
