#pragma once

#include <Windows.h>
#include <synchapi.h>
#include <queue>
#include <vector>
#include <bitset>
#include <unordered_map>
#include <stdio.h>
#include <assert.h>
#include <type_traits>
#include <chrono>
#include <iostream>
#include <array>
#include <type_traits>
#include <fstream>
#include <sstream>
#include "glad/glad.h"
#include "GLFW/glfw3.h"
#include "glm.hpp"
#include "gtc/type_ptr.hpp"
#include "stb_image.h"
#include "Core.h"
